name: UnlimitedNameTags
version: '${version}'
main: org.alexdev.unlimitednametags.UnlimitedNameTags
api-version: '1.19'
author: AlexDev_
folia-supported: true
libraries:
  - de.exlll:configlib-yaml:${configlibVersion}
  - de.exlll:configlib-paper:${configlibVersion}
  - net.jodah:expiringmap:${expiringMapVersion}
  - org.apache.commons:commons-jexl3:${commonsJexl3Version}
depend:
  - packetevents
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Oraxen
permissions:
  unt.shownametags:
    default: true
  unt.showownnametag:
    default: true
